name: Cocos WebGL Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"


    - name: Push built site to main branch
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b gh-pages
        git add _site
        git commit -m "Deploy Jekyll site"
        git push origin gh-pages --force
